name: pipeline-cicd
on:
  push:
    branches:
    - main
  workflow_dispatch: 
jobs: 
  first_job:
    name: primeiro job
    runs-on: ubuntu-22.04
    steps:
    - name: primeira ação
      run: |
        echo "primeira ação"
    - name: segunda ação
      run: |
        echo "segunda ação"

  second_job:
    name: Instalação do ambiente NodeJS
    runs-on: ubuntu-22.04
    needs: 
    - first_job
    steps:
      - name: Verificação da versão do NodeJS
        run: |
          node --version
      - name: Atualização do NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 20.13.1
      - name: Conferindo versão NodeJS
        run: |
          node --version
          
        
  
